pedestrian_simulator:
  static: true
  node:
    debug_output: false
    scenario: random_fast/12_straight.xml
    # GMPCC
    update_frequency: 20 # JACKAL   NOTE THIS SETTING
    prediction_step: 0.2 #0.05 # JACKAL
    horizon: 30 # JACKAL
    use_path_origin: true
  pedestrians:
    seed: 5  # > 0,  -1 = random!
    type: gaussian
    process_noise: [0.0, 0.0] # Deterministic
    velocity: 1.3
    # velocity: 0.
  binomial:
    p: 0.025 #0.01 # 0.05
  social_forces:
    strength: 3.0
    decay: 0.5 # Larger means less rapid decay e^(-b/B)
    line_of_sight: 0.7 #0.7 # Between 0 - 1
